### ISSUE TITLE
HASURA Table -> poll_anwers -> typo

### ISSUE THREAD

**Issue by webrooster** [tomschall/casfee2020-react-spa-ts#12]
**Typo**: Fix typo in table name "poll_anwers" to "poll_answers"

**Comment by tomschall** [comment]
@webrooster Was ist das denn genau ? Hast du das schon gefixt ?

**Comment by webrooster** [comment]
Es ist ein Schreibfehler. Kuckst du! poll_anwers vs. poll_answers. In Anbetracht des aktuellen Standes können wir das vernachlässigen. Ich schliesse dieses Ticket.
