### ISSUE TITLE
Channel Threads: Row mit timestamp ergänzen

### ISSUE THREAD

**Issue by webrooster** [tomschall/casfee2020-react-spa-ts#2]
**Situtation:** Wenn ein User eine Chat-Nachricht kommentiert, sollten man sehen um welche Zeit der Kommentar gemacht wurde. In der Tabelle "channel_thread_message" ist keine Row für den Zeitstempel vorhanden.

**Task**: Tabelle "channel_thread_message" wie in Tabelle "message" mit dem Feld "timestamp" ergänzen.

**Comment by tomschall** [comment]
Fixed!!
